### ISSUE TITLE
Crashes at loading screen when starting new game

### ISSUE THREAD

**Issue by ahstro** [fgsfdsfgs/dhewm3#1]
Using the latest version from the Homebrew App Store. Switch firmware is 6.2.0 with Atmosphère 0.8.3. Can't find any logs for dhewm3 anywhere.

**Comment by fgsfdsfgs** [comment]
Are you running it as a regular app or do you have the default hbloader/hbmenu setup where it replaces the Album?

**Comment by ahstro** [comment]
Ah! Used to run it from the default setup but recently switched to the [full RAM setup](https://gbatemp.net/threads/use-atmosphere-to-access-full-ram-with-homebrews-without-nsp.521240/) and now it works! :smile: Thanks!
